#!/bin/bash


docker run --name="elastic" --restart=always -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.2.2 
pm2 start app.js
sudo service mongod start
